/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema.view;

import Sistema.controller.ClienteController;
import Sistema.model.entity.Clientes;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Cad_Clientes extends javax.swing.JFrame {

    
    ClienteController controller = new ClienteController();
    DefaultTableModel lista = new DefaultTableModel();    // Usa na MontLista
    

    public void recupera_campos(int ar) {

        // teste da var AR
        switch (ar) {
            case 0: // vazio é consulta
                labFuncao.setText("");
                break;
            case 1:
                labFuncao.setText("Incluir");
                break;
            case 2:
                labFuncao.setText("Editar");
                break;
            //
            //defalult = essa função é o otherwise
        }

    }

    public void MontaLista() {

        lista.setColumnCount(0);
        lista.setRowCount(0);

        controller.conecta();
        String sql = "SELECT * FROM CLIENTES "
                + "WHERE UPPER(NOME) "
                + "LIKE '%" + "%'"
                + "ORDER BY NOME";
        

        controller.executeConsulta(sql);

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  // Selecionar apenas um elemento da tabela
        jTable1.getTableHeader().setReorderingAllowed(false);  // Cabecalho nao reordenavel

        lista.addColumn("Cód");
        lista.addColumn("Nome");
        lista.addColumn("Endereço");
        lista.addColumn("Telefone");
        lista.addColumn("CPF");
        jTable1.setModel(lista);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(0).setResizable(false);

        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(4).setResizable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);

        List<Clientes> clientes = controller.getClientes();
        clientes.forEach(cliente ->{
            lista.addRow(new String[]{
                cliente.getId() + "",
                cliente.getNome(),
                cliente.getEndereco(),
                cliente.getTelefone(),
                cliente.getCpf()
            });
        });
        lista.addColumn(clientes);
        controller.desconecta();
        jTable1.setModel(lista);
    }

    public void Selecao() {

        int linha = jTable1.getSelectedRow();  // esta instrução pega o "numero da linha" da grade e coloca na var. "linha"
        // JOptionPane.showMessageDialog(null, "Linha: "+ linha);  // Libere esta instrução e veja o nume da linha da grade

        txtCodigo.setText(jTable1.getValueAt(linha, 0).toString());
        txtNome.setText(jTable1.getValueAt(linha, 1).toString());
        txtEndereco.setText(jTable1.getValueAt(linha, 2).toString());
        txtTelefone.setText(jTable1.getValueAt(linha, 3).toString());
        txtCPF.setText(jTable1.getValueAt(linha, 4).toString());

    }

    public Cad_Clientes() {
        initComponents();

        labTitulo.setText("Cadastros");  // Exemplo: Cadastros
        labTela.setText("Clientes");    // Exemplo: Clientes
        labFuncao.setText("");     // ->     Este define nos Botoes

        MontaLista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        labTitulo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labTela = new javax.swing.JLabel();
        labFuncao = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        Endereço = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(155, 155, 155), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(155, 155, 155));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(730, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(172, 47, 5));
        btnSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("x");
        btnSair.setToolTipText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 2, 27, 22));

        btnMinimizar.setBackground(new java.awt.Color(204, 102, 0));
        btnMinimizar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("-");
        btnMinimizar.setToolTipText("Minimizar");
        btnMinimizar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 2, 27, 22));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 108, 196));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("G&J");
        jLabel7.setAlignmentX(30.0F);
        jLabel7.setAlignmentY(20.0F);
        jLabel7.setAutoscrolls(true);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 54, 18));

        labTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labTitulo.setText("Titulo");
        jPanel2.add(labTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 4, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 729, 25));

        txtNome.setBackground(new java.awt.Color(242, 248, 254));
        txtNome.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNome.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 76, 120, 28));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(94, 138, 204));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(730, 30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTela.setForeground(new java.awt.Color(255, 255, 255));
        labTela.setText("Tela");
        jPanel3.add(labTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 4, -1, -1));

        labFuncao.setBackground(new java.awt.Color(242, 248, 254));
        labFuncao.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labFuncao.setForeground(new java.awt.Color(255, 255, 0));
        jPanel3.add(labFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 3, 110, 21));

        btnAlterar.setBackground(new java.awt.Color(188, 218, 247));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(51, 102, 255));
        btnAlterar.setText("a");
        btnAlterar.setToolTipText("Editar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 28));

        btnDesfazer.setBackground(new java.awt.Color(188, 218, 247));
        btnDesfazer.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnDesfazer.setForeground(new java.awt.Color(51, 102, 255));
        btnDesfazer.setText("D");
        btnDesfazer.setToolTipText("Desfazer");
        btnDesfazer.setEnabled(false);
        btnDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfazerActionPerformed(evt);
            }
        });
        jPanel3.add(btnDesfazer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 28));

        btnCancelar.setBackground(new java.awt.Color(188, 218, 247));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(51, 102, 255));
        btnCancelar.setText("c");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 28));

        btnLocalizar.setBackground(new java.awt.Color(188, 218, 247));
        btnLocalizar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnLocalizar.setForeground(new java.awt.Color(51, 102, 255));
        btnLocalizar.setText("L");
        btnLocalizar.setToolTipText("Localizar");
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 40, 28));

        btnGravar.setBackground(new java.awt.Color(188, 218, 247));
        btnGravar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnGravar.setForeground(new java.awt.Color(51, 102, 255));
        btnGravar.setText("S");
        btnGravar.setToolTipText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 28));

        btnIncluir.setBackground(new java.awt.Color(188, 218, 247));
        btnIncluir.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnIncluir.setForeground(new java.awt.Color(51, 102, 255));
        btnIncluir.setText("I");
        btnIncluir.setToolTipText("Adicionar");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 28));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 25, 724, 27));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 690, 120));

        txtCPF.setBackground(new java.awt.Color(242, 248, 254));
        txtCPF.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 76, 120, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("CPF");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(242, 248, 254));
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(51, 102, 255));
        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 60, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Código");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Telefone");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        txtTelefone.setBackground(new java.awt.Color(242, 248, 254));
        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 76, 130, 28));

        txtEndereco.setBackground(new java.awt.Color(242, 248, 254));
        txtEndereco.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 76, 120, 28));

        Endereço.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Endereço.setText("Endereço");
        jPanel1.add(Endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 732, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // botao [X]
        // this.dispose();  // só o dispose vai fechar tudo
        setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed

        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (!"".equals(txtCodigo.getText())) {
            controller.conecta();
            controller.executaAtualizacao(" UPDATE clientes SET nome = '" + txtNome.getText() + "' WHERE cod_cliente = '" + txtCodigo.getText() + "'");
            controller.executaAtualizacao(" UPDATE clientes SET endereco = '" + txtEndereco.getText() + "' WHERE cod_cliente = '" + txtCodigo.getText() + "'");
            controller.executaAtualizacao(" UPDATE clientes SET telefone = '" + txtTelefone.getText() + "' WHERE cod_cliente = '" + txtCodigo.getText() + "'");
            controller.executaAtualizacao(" UPDATE clientes SET cpf = '" + txtCPF.getText() + "' WHERE cod_cliente = '" + txtCodigo.getText() + "'");

            controller.desconecta();
            MontaLista();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfazerActionPerformed
        txtNome.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtCPF.setText("");
        btnAlterar.setEnabled(false);
        btnGravar.setEnabled(false);
        btnDesfazer.setEnabled(false);
    }//GEN-LAST:event_btnDesfazerActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (!"".equals(txtNome.getText()) && !"".equals(txtCPF.getText())
                && !"".equals(txtCPF.getText()) && !"".equals(txtTelefone.getText())) {

            String nome = txtNome.getText();
            String endereco = txtEndereco.getText();
            String telefone = txtTelefone.getText();
            String cpf = txtCPF.getText();

            controller.conecta();
            controller.executaAtualizacao("INSERT INTO CLIENTES "
                    + "(nome, endereco, telefone, cpf)  VALUES ('"
                    + nome + "','"
                    + endereco + "','"
                    + telefone + "','"
                    + cpf + "')");

            controller.desconecta();
            MontaLista();

            btnAlterar.setEnabled(false);
            btnGravar.setEnabled(false);
            btnDesfazer.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");
        }


    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        btnAlterar.setEnabled(true);
        btnGravar.setEnabled(true);
        btnDesfazer.setEnabled(true);
        
        txtNome.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtCPF.setText("");
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Selecao();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Endereço;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labFuncao;
    private javax.swing.JLabel labTela;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
